spring:
  datasource:
    primary:  #ITMS
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver  #sqlserver
      jdbc-url: jdbc:sqlserver://172.60.6.115;DatabaseName=ITMS   #双数据源更改为jdbc-url
      username: sa
      password: lw2019.
    second:   #SAP_USERS
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver  #sqlserver
      jdbc-url: jdbc:sqlserver://172.60.6.27;DatabaseName=HRM
      username: sa
      password: sa@!admin1
    #测试环境  2012
#    url: jdbc:sqlserver://172.60.45.198;DatabaseName=HRM
#    username: sa
#    password: Lw123456
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2008Dialect
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false #\u663E\u793A\u67E5\u8BE2\u8BED\u53E5
  devtools:
    restart:
      enabled: true
      exclude: WEB/INF/**
      additional-paths: src/main/java
  thymeleaf:
    cache: false  #\u7981\u6B62\u7F13\u5B58
  servlet:
    multipart:
      max-file-size: 20MB  #\u6700\u5927\u4E0A\u4F20\u6587\u4EF6\u5355\u4E2A\u6700\u5927\u503C
      max-request-size: 50MB #\u4E0A\u4F20\u6587\u4EF6\u603B\u7684\u6700\u5927\u503C
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
server:
  port: 8091